### ISSUE TITLE
face and emotion not working for some images

### ISSUE THREAD

**Issue by NeerT** [CognitiveJ/cognitivej#1]
Sometimes the single face detection fails also emotion detection fails, I am attaching 2 images where the face detection and emotion detection failed.
no emotion was detected.

failed to detect the single face

**Comment by CognitiveJ** [comment]
The underlying MS Services can't detect the face as these are not clear in the passed pictures and there is a level of tolerance the these picture fall out of. Please retry with the full face in the picture and the libraries will pick up the face
