### ISSUE TITLE
building on recent Java versions

### ISSUE THREAD

**Issue by SingingBush** [CognitiveJ/cognitivej#13]
the code in this repo won't build as-is with recent JDK releases such as Java 17. It will at least require a newer version of Gradle. It would be great a github action can be setup to build using multiple JDK versions to ensure maximum compatibility. Personally I would like to see JPMS support which would also mean dropping Java 1.8 support. 

Are there any plans for development to continue on this repo? I'm happy to make a PR for a working CI that builds on JDK 8, 11, 17, and 18 if so.

**Comment by kellizer** [comment]
Unfortunately, the project hasn't been active in a while - i expect it all still works as intended but i haven't had the time to continue development or validate compatibility but I'm happy to have you become an admin if you wish to continue to progress this project?

**Comment by SingingBush** [comment]
That would be handy. I'm happy to keep it updated from time to time, in terms of general maintenance. I don't have enough time to work on new features though
