### ISSUE TITLE
findEmotionFaces(InputStream image) returns List<Face> instead of List<Emotion>

### ISSUE THREAD

**Issue by DmitriyMV** [CognitiveJ/cognitivej#3]
I suppose the whole function is duplicate of another one above

Relevant part:
https://github.com/CognitiveJ/cognitivej/blob/9ebcd5e95c9aa75a3fe283f87c3ec3d3bf73963b/src/main/java/cognitivej/vision/face/scenario/FaceScenarios.java#L405

**Comment by konradr25** [comment]
Solved: https://github.com/CognitiveJ/cognitivej/pull/7/commits/b99a4e81b3e30629b4a0aa5630ac62df7146996e
