### ISSUE TITLE
can't search the maven jar on maven mvnrepository

### ISSUE THREAD

**Issue by corningsun** [CognitiveJ/cognitivej#4]
http://search.maven.org/#search%7Cga%7C1%7Ccognitivej

http://www.mvnrepository.com/search?q=cognitivej

**Comment by sarxos** [comment]
Yup, that sucks. To workaround this issue one have to add this repository into the pom:

```xml
<repositories>
	<repository>
		<id>jcenter</id>
		<name>jcenter</name>
		<url>http://jcenter.bintray.com</url>
	</repository>
</repositories>
```
